### PR TITLE
Space is badass

### PR DESCRIPTION
**Pull request by dnmiller**

### CODE REVIEW

**Comment by jneubrand** [comment]
:+1:

**Comment by wardowsmcc** [comment]
Could you make a badass word into animation like this?

**Comment by jneubrand** [comment]
@wardowsmcc 

Space is more badass than language can ever be.
Space isn't just distilled awesomeness.
Space is badassery as nature intended.

**Comment by wardowsmcc** [comment]
badass

**Comment by jneubrand** [comment]
:sunglasses:

**Pull request merged**
