### PR TITLE
Create badass_emoji.md

### PR DESCRIPTION
**Pull request by TylerL-uxai**
Bad ass over here...

### CODE REVIEW

**Comment by jneubrand** [comment]
It may make sense to have a list of all emoji which can reasonably be considered badass, for example :sunglasses:, :moneybag:, :money_with_wings:, :dollar:, :slot_machine:, :bank:, and :gem:. I'd like to see more suggestions for these.

**Comment by wardowsmcc** [comment]
Once this will have more badassism, it will be merged. Emoticon Art memes allowed.

**Comment by TylerL-uxai** [comment]
Yes how about putting it on master so people who enjoy emoji art can add to it?

**Comment by wardowsmcc** [comment]
Feel free to create another pull request.

**Pull request merged**
