### PR TITLE
Add a badass newline at end of file

### PR DESCRIPTION
**Pull request by nocarryr**

### CODE REVIEW

**Comment by aryeguy** [comment]
:+1:

**Comment by filipedeschamps** [comment]
This is a badass PR

**Comment by yangwao** [comment]
Badass newline.

**Comment by timqian** [comment]
You made my day :smiling_imp:

**Comment by azizov4singree** [comment]
I think we need to setup some badass CI for this

**Comment by nocarryr** [comment]
@azizov4singree I was thinking the same thing.  This needs some badass tests to assert its badassness

**Comment by nocarryr** [comment]
:+1:

**Pull request merged**
